services:
  - type: web
    name: produceorderapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATA_DIR
        value: /data
    disk:
      name: produceorderapp-data
      mountPath: /data
      sizeGB: 1
